server.port=8080
spring.application.name=observability-order-service
spring.datasource.url=jdbc:postgresql://localhost:5432/{DB_name}
spring.datasource.username={username}
spring.datasource.password={password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Delay simulation (Day-2)
app.delay.enabled=true
app.delay.millis=2000
///